version: 2
jobs:
  build:
    docker:
      - image: rust:1.31
    steps:
      - checkout
      - run:
          name: Stable Build
          command: |
            cargo build
  test:
    docker:
      - image: rust:1.31
    steps:
      - checkout
      - run:
          command: cargo test